### PR TITLE
Filter out input values before coin selection (fix #3246).

### LINKED ISSUE #3246: Token value may get double spent in Ada refund TxOut
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code

## Summary

I have a wallet like this ... 

```
Wallet 1: 
    {7b3492144d8c9f524fb732c83151afa47d02fb60aff326af0444e0cf2df6c9d7, "Astor260"}: 80
    {7b3492144d8c9f524fb732c83151afa47d02fb60aff326af0444e0cf2df6c9d7, "DLock"}: 1
    {, ""}: 99999870
Script 497801455472ec1d0e8558b5b2b2d489f7f7cdb249aca28a63c86c416be278e7: 
    {, ""}: 100
```
and would now like to pay the DLock token from Wallet 1 together with 80 ADA from the Script to the script and assign it some Datum, with code like this ...

```
  ownerUtxos    <- utxoAt (pubKeyAddress pk)
  scrptUtxos    <- utxoAt (scrAddress pkh)
  dlref         <- findDLockUTxO dlval ownerUtxos
  (rwref,rwval) <- findRewardUTxO amount scrptUtxos
  let
    inidat  = initDatum epoch amount
    payval  = lovelaceValueOf amount
    datval  = dlval <> payval
    rstval  = rwval - payval
    red     = Redeemer $ PlutusTx.toData UnlockAction
    utxoss  = Map.union ownerUtxos scrptUtxos
    lookups = Constraints.scriptInstanceLookups (inst pkh) <>
              Constraints.otherScript (validator pkh) <>
              Constraints.unspentOutputs ownerUtxos <>
              Constraints.unspentOutputs scrptUtxos
    cnstrns = mustSpendPubKeyOutput dlref <>
              mustSpendScriptOutput rwref red <>
              mustPayToTheScript inidat datval <>
              mustPayToTheScript emptyDatum rstval
  tx <- submitTxConstraintsWith lookups cnstrns
  logMyTx "Unlock Tx" $ mytxFromTx tx (txoutRefsFromUTxO utxoss)
  void $ awaitTxConfirmed $ txId tx
  logInfo @String $ printf "Unlocked: %s" (show inidat)
```

The resulting Tx looks like this ...

```
Slot 00004: *** CONTRACT LOG: "Unlock Tx"
Slot 00004: *** CONTRACT LOG: "---------"
Slot 00004: *** CONTRACT LOG: " TxIn mytxRef = TxOutRef {txOutRefId = 90558dc771c9535743af409a6445e94e58c8cd9058ce190a13d68d60638b8301, txOutRefIdx = 1}"
Slot 00004: *** CONTRACT LOG: " -> Just TxOut {mytxAddress = PubKeyCredential 21fe31dfa154a261626bf854046fd2271b7bed4b6abe45aa58877ef47f9721b9, mytxValue = [(7b3492144d8c9f524fb732c83151afa47d02fb60aff326af0444e0cf2df6c9d7,\"DLock\",1)], mytxDatum = Nothing}"
Slot 00004: *** CONTRACT LOG: " TxIn mytxRef = TxOutRef {txOutRefId = ba451ae6915420036179922d9db3fb231033399ff8b9a9101862cb4a4889859d, txOutRefIdx = 0}"
Slot 00004: *** CONTRACT LOG: " -> Just TxOut {mytxAddress = PubKeyCredential 21fe31dfa154a261626bf854046fd2271b7bed4b6abe45aa58877ef47f9721b9, mytxValue = [(,\"\",99999870)], mytxDatum = Nothing}"
Slot 00004: *** CONTRACT LOG: " TxIn mytxRef = TxOutRef {txOutRefId = e2befdda2ca4b3967c0d320a8e7f95d9763bd367715a30903fbaed1878a7143a, txOutRefIdx = 1}"
Slot 00004: *** CONTRACT LOG: " -> Just TxOut {mytxAddress = ScriptCredential 497801455472ec1d0e8558b5b2b2d489f7f7cdb249aca28a63c86c416be278e7, mytxValue = [(,\"\",100)], mytxDatum = Nothing}"
Slot 00004: *** CONTRACT LOG: " TxOut {mytxAddress = PubKeyCredential 21fe31dfa154a261626bf854046fd2271b7bed4b6abe45aa58877ef47f9721b9, mytxValue = [(7b3492144d8c9f524fb732c83151afa47d02fb60aff326af0444e0cf2df6c9d7,\"DLock\",1),(,\"\",99999860)], mytxDatum = Nothing}"
Slot 00004: *** CONTRACT LOG: " TxOut {mytxAddress = ScriptCredential 497801455472ec1d0e8558b5b2b2d489f7f7cdb249aca28a63c86c416be278e7, mytxValue = [(,\"\",20)], mytxDatum = Nothing}"
Slot 00004: *** CONTRACT LOG: " TxOut {mytxAddress = ScriptCredential 497801455472ec1d0e8558b5b2b2d489f7f7cdb249aca28a63c86c416be278e7, mytxValue = [(7b3492144d8c9f524fb732c83151afa47d02fb60aff326af0444e0cf2df6c9d7,\"DLock\",1),(,\"\",80)], mytxDatum = Just (MyDatum {pdEpoch = 260, pdActive = True, pdPayout = 80})}"
```

Note, how it pays the DLock token, which only exists once, both to Wallet 1 and to the Script. The resulting Tx fails with ValueNotPreserved

```
Slot 00004: TxnValidationFail 501328795923d3ae34e4dd08dd2105d2060752921f29f03c73687bf4df1967fe: ValueNotPreserved (Value (Map [(,Map [("",99999970)]),(7b3492144d8c9f524fb732c83151afa47d02fb60aff326af0444e0cf2df6c9d7,Map [("DLock",1)])])) (Value (Map [(,Map [("",99999970)]),(7b3492144d8c9f524fb732c83151afa47d02fb60aff326af0444e0cf2df6c9d7,Map [("DLock",2)])]))
```

## Steps to reproduce

The code is here
https://github.com/tdiesler/plutus-pioneer-program/blob/pl3246/code/payout/src/Astor/Payout.hs#L302

You can run testA to reproduce this

### PR DESCRIPTION
**Pull request by ak3n**
This PR fixes the problem occurred in #3246 where the token gets passed into two transactions for pubkey and script using `mustSpendPubKeyOutput` constraint.

---

Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

File: plutus-contract/src/Plutus/Contract/Wallet.hs [hunk 1]
```diff
@@ -165,18 +165,22 @@ balanceTx utxo pk UnbalancedTx{unBalancedTxTx} = do
...
--- | @addInputs mp pk vl tx@ selects transaction outputs worth at least
---   @vl@ from the UTXO map @mp@ and adds them as inputs to @tx@. A public
---   key output for @pk@ is added containing any leftover change.
+-- | @addInputs mp iv pk vl tx@ selects transaction outputs worth at least
+--   @vl@ from the UTXO map @mp@, with filtered out values from @iv@ that are already presented in unbalanced tx,
+--   and adds them as inputs to @tx@. A public key output for @pk@ is added containing any leftover change.
 addInputs
     :: Member (Error WalletAPIError) effs
     => UtxoMap
+    -> [Value]
```
Comment (j-mueller) [inline plutus-contract/src/Plutus/Contract/Wallet.hs:174]: I think we should filter on `TxOutRef` (get the `TxOutRefs` from the inputs of the unbalanced transaction, and then use something like `Map.withoutKeys` on the utxo map). Using the `Value` of an output to identify the output seems quite brittle.

And then we might as well filter `mp` before calling `addInputs`

Comment (ak3n) [reply plutus-contract/src/Plutus/Contract/Wallet.hs]: Fixed 👌

**Review by j-mueller — APPROVED** [review]
LGTM!
