### PR TITLE
Use the argument types of the worker instead of wrapper (fix #4263).

### LINKED ISSUE #4263: Unexpected PLC errors during compilation.
## Summary

In trying to add a data type `Epoch` to a UTxO datum
`TreasuryState`, I encountered a couple of PLC errors during
compilation. With:

```haskell 
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE TemplateHaskell #-}

import Data.Aeson (FromJSON, ToJSON)
import Data.OpenApi.Schema (ToSchema)
import GHC.Generics (Generic)
import PlutusTx qualified
import PlutusTx.Natural (Natural)
import PlutusTx.Prelude 
import Prelude (Show)
import Prelude qualified (Eq)

data TreasuryState = TreasuryState
  { executive :: Credential
  , lastRewardEpoch :: Epoch
  }
  deriving stock (Prelude.Eq, Show, Generic)
  deriving anyclass (FromJSON, ToJSON)

PlutusTx.unstableMakeIsData ''TreasuryState

data Epoch = Epoch
  { epochNumber :: Natural
  }
  deriving stock (Prelude.Eq, Show, Generic)
  deriving anyclass (ToJSON, FromJSON, ToSchema)

instance Eq Epoch where
  {-# INLINEABLE (==) #-}
  e == e' = e.epochNumber == e'.epochNumber

PlutusTx.unstableMakeIsData ''Epoch
PlutusTx.makeLift ''Epoch
```

I experienced error trace (A), listed in "Screenshots and
attachments" below. Please note that `LiqwidX.Treasury.Init` is
the module, which calls `mkTypedValidatorParam` on
`TreasuryState`'s script. Making the components of `TreasuryState`
strict:

```haskell
data TreasuryState = TreasuryState
  { executive :: !Credential
  , lastRewardEpoch :: !Epoch
  }
  deriving stock (Prelude.Eq, Show, Generic)
  deriving anyclass (FromJSON, ToJSON)
```

results in error trace (B). It is only when I alter `Epoch` to be
a `newtype` wrapper: 

```haskell
newtype Epoch = Epoch
  { epochNumber :: Natural
  }
  deriving stock (Show, Prelude.Eq, Generic)
  deriving anyclass (ToJSON, FromJSON, ToSchema)
```

or add an additional record constructor:

```haskell 
data Epoch = Epoch
  { epochNumber :: Natural
  , foo :: Natural
  }
  deriving stock (Show, Prelude.Eq, Generic)
  deriving anyclass (ToJSON, FromJSON, ToSchema)
```

that the project compiles without issue.

## Steps to reproduce

For each example listed in the summary:

1. Duplicate the relevant code snippet.
2. Attempt to place it "on-chain" by compiling a `TypedValidator`
   using `TreasuryState`.
3. Run `cabal v2-build` on your project.

## Expected behavior

That the code compiles without issue.

## System info (please complete the following information):

- OS: Fedora 35
- Version: Kernel 5.14.18-300.fc35.x86_64 
- Plutus version or commit hash:
  3f089ccf0ca746b399c99afe51e063b0640af547

### Error Trace (A)

``` 
...
[63 of 67] Compiling LiqwidX.Treasury.Init ( src/LiqwidX/Treasury/Init.hs, /home/jack/repos/lqx/dist-newstyle/build/x86_64-linux/ghc-8.10.4.20210212/liqwidx-contracts-0.1/build/LiqwidX/Treasury/Init.o, /home/jack/repos/lqx/dist-newstyle/build/x86_64-linux/ghc-8.10.4.20210212/liqwidx-contracts-0.1/build/LiqwidX/Treasury/Init.dyn_o ) [LiqwidX.Treasury changed]
GHC Core to PLC plugin: E016:Error: Error from the PIR compiler:
            E016: Error during PIR typechecking:
            Type mismatch at () in term
              '(lam
                ds
                [ [ Tuple2 (con bytestring) ] (con bytestring) ]
                (lam
                  ds
                  [ [ Tuple2 (con bytestring) ] (con bytestring) ]
                  (lam
                    ds
                    Credential
                    (lam
                      dt
                      (con integer)
                      (let
                        (nonrec)
                        (termbind
                          (nonstrict)
                          (vardecl
                            wild
                            [ [ Tuple2 (con bytestring) ] (con bytestring) ]
                          )
                          ds
                        )
                        [
                          {
                            [
                              {
                                { Tuple2_match (con bytestring) }
                                (con bytestring)
                              }
                              ds
                            ]
                            [
                              [
                                (lam
                                  k
                                  (type)
                                  (lam v (type) [ List [ [ Tuple2 k ] v ] ])
                                )
                                (con bytestring)
                              ]
                              [
                                [
                                  (lam
                                    k
                                    (type)
                                    (lam v (type) [ List [ [ Tuple2 k ] v ] ])
                                  )
                                  (con bytestring)
                                ]
                                (con integer)
                              ]
                            ]
                          }
                          (lam
                            c
                            (con bytestring)
                            (lam
                              t
                              (con bytestring)
                              [
                                [
                                  {
                                    Cons
                                    [
                                      [ Tuple2 (con bytestring) ]
                                      [
                                        [
                                          (lam
                                            k
                                            (type)
                                            (lam
                                              v
                                              (type)
                                              [ List [ [ Tuple2 k ] v ] ]
                                            )
                                          )
                                          (con bytestring)
                                        ]
                                        (con integer)
                                      ]
                                    ]
                                  }
                                  [
                                    [
                                      {
                                        { Tuple2 (con bytestring) }
                                        [
                                          [
                                            (lam
                                              k
                                              (type)
                                              (lam
                                                v
                                                (type)
                                                [ List [ [ Tuple2 k ] v ] ]
                                              )
                                            )
                                            (con bytestring)
                                          ]
                                          (con integer)
                                        ]
                                      }
                                      c
                                    ]
                                    [
                                      [
                                        {
                                          Cons
                                          [
                                            [ Tuple2 (con bytestring) ]
                                            (con integer)
                                          ]
                                        }
                                        [
                                          [
                                            {
                                              { Tuple2 (con bytestring) }
                                              (con integer)
                                            }
                                            t
                                          ]
                                          (con integer 100)
                                        ]
                                      ]
                                      {
                                        Nil
                                        [
                                          [ Tuple2 (con bytestring) ]
                                          (con integer)
                                        ]
                                      }
                                    ]
                                  ]
                                ]
                                {
                                  Nil
                                  [
                                    [ Tuple2 (con bytestring) ]
                                    [
                                      [
                                        (lam
                                          k
                                          (type)
                                          (lam
                                            v (type) [ List [ [ Tuple2 k ] v ] ]
                                          )
                                        )
                                        (con bytestring)
                                      ]
                                      (con integer)
                                    ]
                                  ]
                                }
                              ]
                            )
                          )
                        ]
                      )
                    )
                  )
                )
              )'.
            Expected type
              '(fun
                [ [ Tuple2_1164 (con bytestring) ] (con bytestring) ]
                (fun
                  [ [ Tuple2_1164 (con bytestring) ] (con bytestring) ]
                  (fun
                    Credential_1479
                    (fun
                      (con integer)
                      [
                        List_1128
                        [
                          [ Tuple2_1164 (con bytestring) ]
                          [
                            List_1128
                            [ [ Tuple2_1164 (con bytestring) ] (con integer) ]
                          ]
                        ]
                      ]
                    )
                  )
                )
              )',
            found type
              '(fun
                [ [ Tuple2_1164 (con bytestring) ] (con bytestring) ]
                (fun
                  [ [ Tuple2_1164 (con bytestring) ] (con bytestring) ]
                  (fun
                    Credential_1479
                    (fun
                      Epoch_1546
                      [
                        List_1128
                        [
                          [ Tuple2_1164 (con bytestring) ]
                          [
                            List_1128
                            [ [ Tuple2_1164 (con bytestring) ] (con integer) ]
                          ]
                        ]
                      ]
                    )
                  )
                )
              )'
Context: Compiling expr at "liqwidx-contracts-0.1-inplace:LiqwidX.Treasury.Init:(75,8)-(75,47)"
cabal: Failed to build liqwidx-contracts-0.1 (which is required by
test:scripts from liqwidx-contracts-0.1, test:script-size from
liqwidx-contracts-0.1 and others).

make: *** [Makefile:114: build] Error 1
```

### Error Trace (B)

```
...
[63 of 67] Compiling LiqwidX.Treasury.Init ( src/LiqwidX/Treasury/Init.hs, /home/jack/repos/lqx/dist-newstyle/build/x86_64-linux/ghc-8.10.4.20210212/liqwidx-contracts-0.1/build/LiqwidX/Treasury/Init.o, /home/jack/repos/lqx/dist-newstyle/build/x86_64-linux/ghc-8.10.4.20210212/liqwidx-contracts-0.1/build/LiqwidX/Treasury/Init.dyn_o ) [LiqwidX.Treasury changed]
GHC Core to PLC plugin: E016:Error: Error from the PIR compiler:
            E016: Error during PIR typechecking:
            Type mismatch at () in term
              'dt'.
            Expected type
              '(con integer)',
            found type
              'Epoch_1552'
Context: Compiling expr at "liqwidx-contracts-0.1-inplace:LiqwidX.Treasury.Init:(75,8)-(75,47)"
cabal: Failed to build liqwidx-contracts-0.1 (which is required by
test:scripts from liqwidx-contracts-0.1, test:script-size from
liqwidx-contracts-0.1 and others).

make: *** [Makefile:114: build] Error 1
```

### PR DESCRIPTION
**Pull request by ak3n**
fix #4263

---

Pre-submit checklist:
- Branch
    - [x] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] (For external contributions) Corresponding issue exists and is linked in the description
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

### CODE REVIEW

File: plutus-tx-plugin/src/PlutusTx/Compiler/Type.hs [hunk 1]
```diff
@@ -236,10 +236,23 @@ getDataCons tc' = sortConstructors tc' <$> extractDcs tc'
           | GHC.isFamilyTyCon tc = throwSd UnsupportedError $ "Irreducible type family application:" GHC.<+> GHC.ppr tc
           | otherwise = throwSd UnsupportedError $ "Type constructor:" GHC.<+> GHC.ppr tc
 
+{- Note [On workers and wrappers]
```
Comment (michaelpj) [inline plutus-tx-plugin/src/PlutusTx/Compiler/Type.hs:239]: Maybe "On data constructor workers and wrappers", since "worker" and "wrapper" come up in lots of other contexts too.

**Review by michaelpj — APPROVED** [review]
Ugh, there's some kind of optimization flip-flopping that means the generated test output doesn't match. Try again?
