### PR TITLE
Filter out empty outputs (fix #3251)

### LINKED ISSUE #3251: Tx balancer may produce outputs with zero value
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code

## Summary

I see TxOut like this ...

```
"| Redeem Tx --------------------------------------------------------------------"
"| TxIn mytxRef = TxOutRef {txOutRefId = a75e48e9d96c03c01a14ed172206a73535ef392810e3fbe4baaef1c90ad6240c, txOutRefIdx = 1}"
"| -> Just TxOut {mytxAddress = PubKeyCredential 21fe31dfa154a261626bf854046fd2271b7bed4b6abe45aa58877ef47f9721b9, mytxValue = [(7b3492144d8c9f524fb732c83151afa47d02fb60aff326af0444e0cf2df6c9d7,\"Astor260\",800)], mytxDatum = Nothing}"
"| TxIn mytxRef = TxOutRef {txOutRefId = c851a47cf74fe8de571aae31eb69b7082bd4670f5d4422a7f9bffd49c8898da2, txOutRefIdx = 2}"
"| -> Just TxOut {mytxAddress = ScriptCredential 08876e59eb085db7b9150f4137a04d11c44fa462175f97c8deddb00439bb0490, mytxValue = [(,\"\",800)], mytxDatum = Just (MyDatum {pdEpoch = 260, pdActive = True, pdPayout = 800})}"
"|--------------"
"| TxOut {mytxAddress = PubKeyCredential 21fe31dfa154a261626bf854046fd2271b7bed4b6abe45aa58877ef47f9721b9, mytxValue = [(,\"\",790)], mytxDatum = Nothing}"
"| TxOut {mytxAddress = ScriptCredential 08876e59eb085db7b9150f4137a04d11c44fa462175f97c8deddb00439bb0490, mytxValue = [(7b3492144d8c9f524fb732c83151afa47d02fb60aff326af0444e0cf2df6c9d7,\"Astor260\",800)], mytxDatum = Just (MyDatum {pdEpoch = 260, pdActive = True, pdPayout = 800})}"
"| TxOut {mytxAddress = PubKeyCredential 21fe31dfa154a261626bf854046fd2271b7bed4b6abe45aa58877ef47f9721b9, mytxValue = [], mytxDatum = Nothing}"
"--------------------------------------------------------------------------------"
```

## Steps to reproduce

Is it correct to have outputs with zero value? If not, I can provide a reproducer.

## Expected behavior

Perhaps the balancer should suppress these outputs? 

## System info (please complete the following information):

- Plutus version: 530cc134364ae186f39fb2b54239fb7c5e2986e9

### PR DESCRIPTION
**Pull request by ak3n**
This PR removes empty outputs mentioned in #3251

---

Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

File: plutus-contract/src/Plutus/Contract/Wallet.hs [hunk 1]
```diff
@@ -193,6 +196,11 @@ addOutputs :: PubKey -> Value -> Tx -> Tx
 addOutputs pk vl tx = tx & over Tx.outputs (pko :) where
     pko = Tx.pubKeyTxOut vl pk
 
+removeEmptyOutputs :: Tx -> Tx
+removeEmptyOutputs tx = tx & over Tx.outputs (filter (not . isEmpty)) where
+    isEmpty (Tx.TxOut{Tx.txOutValue, Tx.txOutDatumHash}) =
+        null (Value.flattenValue txOutValue) && isNothing txOutDatumHash
```
Comment (michaelpj) [inline plutus-contract/src/Plutus/Contract/Wallet.hs:202]: Right, so this is not removing script outputs, which makes sense. Then I guess we're just going to get an error later that we can't create an output with nothing in it, but I'm not sure there's anything we can do about that.

Comment (michaelpj) [reply plutus-contract/src/Plutus/Contract/Wallet.hs:202]: Worth a comment though.

**Review by michaelpj — APPROVED** [review]

**Comment by michaelpj** [comment]
conflicts
