### PR TITLE
Fix isEmpty for some open intervals (#3467).

### LINKED ISSUE #3467: isEmpty fails for some open intervals
## Summary

isEmpty in the ledger Interval module can return the wrong result, for intervals with open endpoints. As a consequence, overlaps can also return a wrong result.

## Steps to reproduce

cabal repl plutus-ledger-api
Prelude Data.Aeson.Extras> import Plutus.V1.Ledger.Interval
Prelude Plutus.V1.Ledger.Interval Data.Aeson.Extras> emptyInterval = Interval (strictLowerBound 4) (strictUpperBound 5) :: Interval Integer
Prelude Plutus.V1.Ledger.Interval Data.Aeson.Extras> nonemptyInterval = interval 4 5 :: Interval Integer
Prelude Plutus.V1.Ledger.Interval Data.Aeson.Extras> emptyInterval
Interval {ivFrom = LowerBound (Finite 4) False, ivTo = UpperBound (Finite 5) False}
Prelude Plutus.V1.Ledger.Interval Data.Aeson.Extras> nonemptyInterval
Interval {ivFrom = LowerBound (Finite 4) True, ivTo = UpperBound (Finite 5) True}
Prelude Plutus.V1.Ledger.Interval Data.Aeson.Extras> [i | i <- [0..10], i `member` emptyInterval]
[]
Prelude Plutus.V1.Ledger.Interval Data.Aeson.Extras> [i | i <- [0..10], i `member` nonemptyInterval]
[4,5]
Prelude Plutus.V1.Ledger.Interval Data.Aeson.Extras> isEmpty nonemptyInterval
False
Prelude Plutus.V1.Ledger.Interval Data.Aeson.Extras> isEmpty emptyInterval
False

Prelude Plutus.V1.Ledger.Interval Data.Aeson.Extras> Interval (strictLowerBound 0) (strictUpperBound 5) `overlaps` Interval (strictLowerBound 4) (strictUpperBound 10)
True

## Expected behavior

The last call, isEmpty emptyInterval, ought to return True, because the interval is, in fact, empty. 

The last line shows a consequence of the bug: these two non-overlapping intervals are considered to overlap (the result should be False).

## System info (please complete the following information):

- OS: Ubuntu
- Version 18.04.5
- Plutus version or commit hash 8c42e1fef419e7b2eaa021af75564862e8fa2999

## Additional context

I can think of two approaches to fixing this. 

* Disallow open interval endpoints, at least for finite values. This would require hiding the constructor of the Interval type, to guarantee the invariant is preserved.
* Require an Enum a context for isEmpty and overlaps, so that an open endpoint can be treated like a closed endpoint with succ <lower_bound> or pred <upper_bound>.

### PR DESCRIPTION
**Pull request by ak3n**
Introduce `Enum` typeclass for Plutus to fix the problem with open intervals (fix #3467).

---

Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

File: plutus-ledger-api/src/Plutus/V1/Ledger/Slot.hs [hunk 1]
```diff
@@ -42,7 +42,8 @@ import           Plutus.V1.Ledger.Interval
 newtype Slot = Slot { getSlot :: Integer }
     deriving stock (Haskell.Eq, Haskell.Ord, Haskell.Show, Generic)
     deriving anyclass (FromJSON, FromJSONKey, ToJSON, ToJSONKey, NFData)
-    deriving newtype (Haskell.Num, AdditiveSemigroup, AdditiveMonoid, AdditiveGroup, Haskell.Enum, Eq, Ord, Haskell.Real, Haskell.Integral, Serialise, Hashable, PlutusTx.IsData)
+    deriving newtype (AdditiveSemigroup, AdditiveMonoid, AdditiveGroup, Eq, Ord, Enum, PlutusTx.IsData)
+    deriving newtype (Haskell.Num, Haskell.Enum, Haskell.Real, Haskell.Integral, Serialise, Hashable)
```
Comment (koslambrou) [inline plutus-ledger-api/src/Plutus/V1/Ledger/Slot.hs:46]: Curious, why not combine the two `deriving newtype`?

Comment (ak3n) [reply plutus-ledger-api/src/Plutus/V1/Ledger/Slot.hs:46]: I decided to split into two groups, Haskell-related and Plutus-related, because the line is too long. If it makes no sense or strange I can get it back.

File: plutus-tx/src/PlutusTx/Enum.hs [hunk 2]
```diff
@@ -0,0 +1,17 @@
+{-# OPTIONS_GHC -fno-omit-interface-pragmas #-}
+module PlutusTx.Enum (Enum(..)) where
+
+import           PlutusTx.Builtins
+import           Prelude           hiding (Enum (..))
+
+class Enum a where
```
Comment (j-mueller) [inline plutus-tx/src/PlutusTx/Enum.hs:7]: Haddocks (copying or referencing the GHC definition is OK)

File: plutus-tx/src/PlutusTx/Enum.hs [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+  succ :: a -> a
+  pred :: a -> a
+  toEnum :: Integer -> a
+  fromEnum :: a -> Integer
+
+instance Enum Integer where
```
Comment (j-mueller) [inline plutus-tx/src/PlutusTx/Enum.hs:13]: This could do with some more instances, `Bool`, `Maybe`, `()`, etc.

Comment (ak3n) [reply plutus-tx/src/PlutusTx/Enum.hs:20]: Added instances for `Bool`, `Ordering` and `()`.

File: plutus-tx/src/PlutusTx/Enum.hs (hunk 2 above)
Comment (ak3n) [reply plutus-tx/src/PlutusTx/Enum.hs:10]: Added some comments. The whole `Enum`'s haddock contains facts about `Enum`'s connection with `Bounded` but we don't have it yet.

File: plutus-tx/src/PlutusTx/Enum.hs [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+
+  {-# INLINABLE toEnum #-}
+  toEnum x = x
+
+  {-# INLINABLE fromEnum #-}
+  fromEnum x = x
+
+instance Enum () where
+  {-# INLINABLE succ #-}
+  succ _ = error (trace "PlutusTx.Enum.().succ: bad argument")
```
Comment (michaelpj) [inline plutus-tx/src/PlutusTx/Enum.hs:35]: `traceError` exists although not a big deal

File: plutus-ledger-api/src/Plutus/V1/Ledger/Interval.hs [hunk 5]
```diff
@@ -260,11 +260,17 @@ contains (Interval l1 h1) (Interval l2 h2) = l1 <= l2 && h2 <= h1
...
 isEmpty (Interval (LowerBound v1 in1) (UpperBound v2 in2)) = case v1 `compare` v2 of
-    LT -> False
+    LT -> if openInterval then checkEnds v1 v2 else False
     GT -> True
     EQ -> not (in1 && in2)
+    where
+        openInterval = in1 == False && in2 == False
+        -- | We check two finite ends to figure out if there are elements between them.
+        -- If there are no elements then the interval is empty (#3467).
+        checkEnds (Finite v1') (Finite v2') = (succ v1') `compare` v2' == EQ
```
Comment (michaelpj) [inline plutus-ledger-api/src/Plutus/V1/Ledger/Interval.hs:272]: I had to think about this a bit. I wonder whether it would be clearer to express it like this:
```
toClosedInterval (Enum a) => Interval a -> Bool
toClosedInterval (Interval l@(LowerBound v1 in1) u@(UpperBound v2 in1)) = 
    Interval (if not in1 then (LowerBound (succ v1) True))) (if not in2 then (UpperBound (pred v2) True) else u)

-- just putting a view pattern here to make it as similar as possible to before
isEmpty (toClosedInterval -> (Interval ...)) = case v1 `compare` v2 of
  LT -> False
  ...
```

That is, what `Enum` gives you is the ability to turn an open endpoints into equivalent closed endpoints, and then we simply only check emptiness on closed intervals.

Comment (michaelpj) [reply plutus-ledger-api/src/Plutus/V1/Ledger/Interval.hs:272]: Up to you, though, my version is more complex.

**Review by michaelpj — APPROVED** [review]

File: plutus-ledger-api/src/Plutus/V1/Ledger/Slot.hs (hunk 1 above)
Comment (koslambrou) [reply plutus-ledger-api/src/Plutus/V1/Ledger/Slot.hs:46]: Good idea

File: plutus-tx/src/PlutusTx/Enum.hs (hunk 4 above)
Comment (ak3n) [reply plutus-tx/src/PlutusTx/Enum.hs:35]: Yeah, it's in `Prelude` module that imports `Enum`. Maybe it's better to move it to it's own module with other trace functions, smth like `Prelude.Trace`?

File: plutus-ledger-api/src/Plutus/V1/Ledger/Interval.hs (hunk 5 above)
Comment (ak3n) [reply plutus-ledger-api/src/Plutus/V1/Ledger/Interval.hs:272]: I agree, your version looks more general and more clear in some sense.

`succ v1` requires `Enum` instance for `Extended a` though... I avoided to write it because less code is better :D
