### PR TITLE
[plutus-tx-plugin]: precompile alternatives during the GHC.Case compilation to reduce the complexity (fix #4204).

### LINKED ISSUE #4204: Long compilation time of plutus scripts
## Summary

Compilation of scripts that have many variables in scope takes a lot of time.

## Steps to reproduce

Compile the following minting policy. Having more variables in scope (`l20`, `l21` etc) causes the compilation time to double.

```
mkPolicy _ ctx =
  let l = length $ Ledger.txInfoInputs $ Ledger.scriptContextTxInfo ctx
      l1 = l + 1
      l2 = l + 2
      l3 = l + 3
      l4 = l + 4
      l5 = l + 5
      l6 = l + 6
      l7 = l + 7
      l8 = l + 8
      l9 = l + 9
      l10 = l + 19
      l11 = l + 11
      l12 = l + 12
      l13 = l + 13
      l14 = l + 14
      l15 = l + 15
      l16 = l + 16
      l17 = l + 17
      l18 = l + 18
      l19 = l + 19
   in -- l20 = l + 20
      l == 0
        && l1 == 0
        && l2 == 0
        && l3 == 0
        && l4 == 0
        && l5 == 0
        && l6 == 0
        && l7 == 0
        && l8 == 0
        && l9 == 0
        && l10 == 0
        && l11 == 0
        && l12 == 0
        && l13 == 0
        && l14 == 0
        && l15 == 0
        && l16 == 0
        && l17 == 0
        && l18 == 0
        && l19 == 0
-- && l20 == 0
```

## Expected behavior

Fast compilation - non dependent on number of variables.

## System info:

- OS: Ubuntu
- Version 21.04
- plutus version: 58c093a49eb7a369865e361179d649264fc817a4

## Additional context

That's a minimal scenario. Not really sure if number of variables in scope or && operator or sth else is a culprit here.

Measurements:
number of variables / compilation time
variables up to l10 uncommented  - 4s
variables up to l15 uncommented  - 17s
variables up to l16 uncommented  - 30s
variables up to l17 uncommented  - 60s
variables up to l18 uncommented  - 110s
variables up to l19 uncommented  - 230s

### PR DESCRIPTION
**Pull request by ak3n**
Fixes #4204.

The compilation time reduced from 1 and more minutes to 42.17 ms.

---

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

### CODE REVIEW

File: plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs [hunk 1]
```diff
@@ -180,7 +182,9 @@ compileAlt mustDelay instArgTys (alt, vars, body) = withContextM 3 (sdToTxt $ "C
     -- vars into scope whose body is the body of the case alternative.
     -- See Note [Iterated abstraction and application]
     -- See Note [Case expressions and laziness]
-    GHC.DataAlt _ -> mkIterLamAbsScoped vars (compileExpr body >>= maybeDelay mustDelay)
+    GHC.DataAlt _ -> mkIterLamAbsScoped vars (compiledBody >>= maybeDelay mustDelay)
+    where
+        compiledBody = fromMaybe (compileExpr body) (pure <$> mCompiledBody)
```
Comment (michaelpj) [inline plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs:187]: ugh, this is all a bit subtle, isn't it? There's a secret correspondance going on, where we won't have precompiled versions of the bodies of the cases that have actual lambdas (which is good, because they'd need the variables to be in scope!), so we will always compile them here.

I believe it all works out, it's just... fiddly. I'm not sure how to make it less fiddly.

Comment (michaelpj) [reply plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs:187]: Hmm, here's an idea. How about we have this function return both the delayed _and_ non-delayed bodies. Then we can 

1. run `compileAlt` up front for all the alternatives
2. look at all the non-delayed alternatives to work out if we need to delay
3. if we need to delay, use the delayed versions, otherwise use the non-delayed versions

That wouldn't be too expensive, since we mostly reuse the work: returning the delayed version as well just means making a small change to the non-delayed version.

WDYT?

**Review by michaelpj — COMMENTED** [review]
I think this probably works, I just had an idea about how we can maybe make it less fiddly.

File: plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs (hunk 1 above)
Comment (ak3n) [reply plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs:187]: Sounds okay.

Will it affect the purity check? As `compileAlt`'s result is a bit different than `compileExpr body`, the behaviour of `PIR.isPure (const PIR.NonStrict)` might change in some cases?

Comment (michaelpj) [reply plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs:187]: so I'm suggesting that `compileAlt` returns `(compileExpr body, delay $ compileExpr body)` (well not quite, since the delay goes inside the lambda for alternatives with arguments, but you get the idea). Then `isPure` on the first component *will* do the right thing.

Importantly, the reason we check whether there are any variables is just a cheap way of short-cutting what would happen if we compiled the body: if the alternative has variables, then it will turn into a lambda, which will be considered pure.

File: plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs [hunk 2]
```diff
@@ -161,26 +161,34 @@ findAlt dc alts t = case GHC.findAlt (GHC.DataAlt dc) alts of
...
+        b <- compileExpr body
+        delayed <- delay b
+        return (PLC.mkIterLamAbs vars' b, PLC.mkIterLamAbs vars' delayed)
+    GHC.DEFAULT   -> do
+        compiledBody <- compileExpr body
+        nonDelayed <- compileDefaultAlt compiledBody
+        delayed <- delay compiledBody >>= compileDefaultAlt
+        return (nonDelayed, delayed)
+    where
+        compileDefaultAlt :: CompilingDefault uni fun m => PIRTerm uni fun -> m (PIRTerm uni fun)
```
Comment (michaelpj) [inline plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs:186]: maybe `wrapDefaultAlt`?

File: plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs [hunk 3]
```diff
@@ -482,7 +490,6 @@ traceInside ::
 traceInside varName lamName = go
     where
         go (LamAbs () n t body) (PLC.TyFun () _dom cod) =
-        -- when t = \x -> body, => \x -> traceInside body
```
Comment (michaelpj) [inline plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs:485]: these comments are useful!

File: plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs [hunk 4]
```diff
@@ -710,27 +715,31 @@ compileExpr e = withContextM 2 (sdToTxt $ "Compiling expr:" GHC.<+> GHC.ppr e) $
...
+                alternatives <- forM dcs $ \dc -> do
+                    let alt = findAlt dc alts t
+                        -- these are the instantiated type arguments, e.g. for the data constructor Just when
+                        -- matching on Maybe Int it is [Int] (crucially, not [a])
+                        instArgTys = GHC.dataConInstOrigArgTys dc argTys
+                    (nonDelayedAlt, delayedAlt) <- compileAlt alt instArgTys
+                    return (alt, nonDelayedAlt, delayedAlt)
+                isPureAlt <- forM alternatives $ \((_, vars, _), nonDelayed, _) ->
+                    pure $ if null vars
+                        then PIR.isPure (const PIR.NonStrict) nonDelayed
```
Comment (michaelpj) [inline plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs:731]: you can just use this branch unconditionally now. Also then you don't need to return `alt` on line 728 either.

**Review by michaelpj — APPROVED** [review]

File: plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs (hunk 3 above)
Comment (ak3n) [reply plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs:485]: sorry, i thought they are forgotten artefacts, got them back!

File: plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs [hunk 5]
```diff
@@ -23,14 +23,13 @@ import PlutusTx.Compiler.Utils
...
-import PlutusTx.Builtins.Class qualified as Builtins
-import PlutusTx.Trace
-
 import Class qualified as GHC
 import CoreSyn qualified as GHC
 import CostCentre qualified as GHC
 import GhcPlugins qualified as GHC
 import MkId qualified as GHC
+import PlutusTx.Builtins.Class qualified as Builtins
+import PlutusTx.Trace
```
Comment (ak3n) [inline plutus-tx-plugin/src/PlutusTx/Compiler/Expr.hs:32]: Oh, that's a great example of how comments in the code get outdated as the code formatter is not smart enough to move them as well.

**Comment by michaelpj** [comment]
If you're bored, I'd be interested to see how much effect this has on the examples in `plutus-use-cases`.
