### PR TITLE
PLT-712: Update and add Haddock to some functions in `plutus-ledger-api`.

### LINKED ISSUE #4476: Undocumented invariants in types with exposed constructors
### Summary

Multiple types have undocumented invariants, and also expose their constructors, in modules that are not marked as unsafe or internal. The following is a (non-exhaustive) list of examples:

* `PubKey` (in all variants) must be 64 bytes long.
* `POSIXTime` must be non-negative.
* `Signature` must be 64 bytes long.
* `DatumHash` must be 28 bytes long.
* `TokenName` must be no longer than 32 bytes, and be hex encoded.
* `TxId` must be 28 bytes long.
* `ValidatorHash` must be 28 bytes long.
* `PubKeyHash` (in all variants) must 28 bytes long.

### Steps to reproduce the behavior

1. Attempt to construct any value of any of the listed types which does not follow the specified invariant(s).
2. Observe how the compiler accepts it.
3. Try to use it on-chain.
4. Watch things blow up.

### Actual Result

Your transactions will fail, usually by erroring out.

### Expected Result

If we can construct a value, it should be usable without erroring. If it has internal invariants, those should be documented at least; better still, the constructors should _not_ be exposed.

### Describe the approach you would take to fix this

At minimum, all such invariants must be documented clearly at the definition site of the type, ideally with reasons why they are so. If this is for stuff that is external to the type, links should be provided in the Haddocks to the relevant information. However, in a more ideal world, the constructors of such types should also _either_ inhabit modules clearly marked as unsafe, _or_ not be exposed at all in favour of safe construction methods, such as smart constructors or quasi-quoters.

### System info

Plutus commit: 3f3f875764f2e329c8d738f99cdef0c1260ccde1

### LINKED ISSUE #4801: Plutus Ledger API haddocks incorrectly state that SHA256 is being used.
### Summary

According to a comment from @JaredCorduan [here](https://github.com/input-output-hk/cardano-ledger/issues/2941#issuecomment-1203012829), all hashes in the cardano-ledger should be blake2b. 

Areas where I _know_ that SHA256 is referenced in the haddocks:

- `ScriptHash`
-  `DatumHash`
- `ValidatorHash`
-  `RedeemerHash` 
- `MintingPolicyHash`
-  `StakeValidatorHash`
- `TxId`.

I'm not sure whether all of these _should_ be blake2b, but Jared has confirmed that at least TxId should be.

### Steps to reproduce the behavior

Look at the source in `src/PlutusLedgerApi/V1/Scripts.hs`, `src/PlutusLedgerApi/V1/Contexts.hs`, `src/PlututsLedgerAPI/V1/Tx.hs`.

### Actual Result

References to `Digest SHA256` and `(...) using a SHA256 hash` appear.

### Expected Result

These should most likely say blake2b, sometimes 224 and sometimes 256.

### Describe the approach you would take to fix this

- Determine which hashes _should_ be blake2b, and which variants.
- `grep -rie "sha256"` and make sure that all of the relevant instances have been updated.

### System info

Latest master (commit 107d7e7ec5a1c033228c402ee221794117566d15)

### PR DESCRIPTION
**Pull request by thealmarty**
The purpose of this is to add/update the Haddock of some functions in the plutus-ledger-api. Closes #4476, closes #4801.

Haddock is added to types mentioned in the issues roughly following this format:

- What is it?
- Its hash algorithm, if any
- No. of bytes, if applicable
- Add warning that these types are simple types without any validation.
- Links to relevant info/spec

I've tried to verify the added info against the spec/code but @michaelpj and @JaredCorduan could you please confirm all the info are accurate. 

@JaredCorduan regarding [your comment](https://github.com/input-output-hk/plutus/issues/4476#issuecomment-1209294094), could you please let us know when the appendix is added so we can add links to the Haddock? Thanks.

I've included most types mentioned in #4476 and #4801. More Haddock is needed and we have follow up tickets to improve our Haddock. But there's demand to merge this part soon.

Pre-submit checklist:
- Branch
    - [x] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
    - [x] Formatting, PNG optimization, etc. are updated
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [x] Targeting master unless this is a cherry-pick backport
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

### CODE REVIEW

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs [hunk 1]
```diff
@@ -17,15 +17,17 @@ import Control.DeepSeq (NFData)
...
-import PlutusTx qualified as PlutusTx
+import PlutusTx qualified
 import PlutusTx.Bool qualified as PlutusTx
 import PlutusTx.Eq qualified as PlutusTx
 import Prettyprinter (Pretty (..), (<+>))
 
--- | Staking credential used to assign rewards
+-- | Staking credential used to assign rewards.
 data StakingCredential
     = StakingHash Credential
```
Comment (JaredCorduan) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs:27]: did you want to mention that this hash is as 28 byte Blake2b 224?

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs [hunk 2]
```diff
@@ -44,8 +46,12 @@ instance PlutusTx.Eq StakingCredential where
 
 -- | Credential required to unlock a transaction output
 data Credential
-  = PubKeyCredential PubKeyHash -- ^ The transaction that spends this output must be signed by the private key
-  | ScriptCredential ValidatorHash -- ^ The transaction that spends this output must include the validator script and be accepted by the validator.
+  =
+    -- | The transaction that spends this output must be signed by the private key.
+    PubKeyCredential PubKeyHash
```
Comment (JaredCorduan) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs:51]: did you want to mention that this hash is as 28 byte Blake2b 224?

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Tx.hs [hunk 3]
```diff
@@ -59,32 +59,40 @@ import PlutusLedgerApi.V1.Bytes
 import PlutusLedgerApi.V1.Crypto
 import PlutusLedgerApi.V1.Scripts
 import PlutusLedgerApi.V1.Value
-
--- | A transaction ID, using a SHA256 hash as the transaction id.
+{- | A transaction ID. Hashed with BLAKE2b-244. 28 byte.
```
Comment (JaredCorduan) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Tx.hs:62]:
```suggestion
{- | A transaction ID. Hashed with BLAKE2b-256. 32 byte.
```

**Comment by thealmarty** [comment]
We normally do a squash and merge but we can also do a rebase and merge for this one to preserve all the commits, if desired.

**Comment by L-as** [comment]
Thank you!

File: plutus-tx/src/PlutusTx/IsData/Class.hs [hunk 4]
```diff
@@ -46,6 +46,7 @@ class UnsafeFromData (a :: Type) where
     --
     -- When implementing this function, make sure to call 'unsafeFromBuiltinData'
     -- rather than 'fromBuiltinData' when converting substructures!
+    -- This is a simple type without any validation, __use with caution__.
```
Comment (bezirg) [inline plutus-tx/src/PlutusTx/IsData/Class.hs:49]: nitpicking: I don't know if your intentions is to have a newline but you need an empty comment line to have a newline. Right now, it is concatenated with the text above.

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Bytes.hs [hunk 5]
```diff
@@ -28,12 +28,14 @@ import PlutusTx
 import PlutusTx.Prelude qualified as P
 import Prettyprinter.Extras (Pretty, PrettyShow (..))
 
+{- | An error that is encountered when converting a `Bytestring` to a `LedgerBytes`. -}
 data LedgerBytesError =
-    UnpairedDigit
-    | NotHexit Char
+    UnpairedDigit -- ^ Odd number of bytes.
+    | NotHexit Char -- ^ Not a hex digit.
```
Comment (bezirg) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Bytes.hs:34]: This will not be shown in haddock output because `LedgerBytesError` is not exported by this module. Which implies we don't have any (regression) tests for the `fromHex` function

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Bytes.hs [hunk 6]
```diff
@@ -76,12 +78,17 @@ bytes = P.fromBuiltin . getLedgerBytes
...
 instance IsString LedgerBytes where
     fromString = unsafeFromEither . fromHex . fromString
 
+{- | The `Show` instance of `LedgerBytes` is its base16/hex encoded bytestring,
+decoded with UTF-8, unpacked to `String`. -}
 instance Show LedgerBytes where
     show = Text.unpack . encodeByteString . bytes
 
+{- | Encode a ByteString value in base16 (i.e. hexadecimal), then
+decode with UTF-8 to a `Text`. -}
```
Comment (bezirg) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Bytes.hs:91]: I have a feeling that going through Text and decodeUTF8 is redundant for showing base16 bytestrings.

Also do you know why we prepend '0x' only for tokennames? https://github.com/input-output-hk/plutus/blob/master/plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs#L115-L116

File: plutus-tx/src/PlutusTx/IsData/Class.hs (hunk 4 above)
Comment (thealmarty) [reply plutus-tx/src/PlutusTx/IsData/Class.hs:49]: I didn't have that intention but that's a good idea.

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Bytes.hs (hunk 6 above)
Comment (thealmarty) [reply plutus-ledger-api/src/PlutusLedgerApi/V1/Bytes.hs:91]: Maybe it's redundant, since `asBase16` is only used to convert to `String` it seems: https://github.com/input-output-hk/plutus/blob/15b9c416ededcd7184db3c4f741737cadb194966/plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs#L121-L125 Not sure if I should be fixing code in this PR though. I think we should do it in the clean up PR? There's a ticket to clean up `plutus-ledger-api`.

I have no idea why we prepend '0x' only for token names.

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Bytes.hs (hunk 5 above)
Comment (thealmarty) [reply plutus-ledger-api/src/PlutusLedgerApi/V1/Bytes.hs:34]: Good point. But let's leave this here anyway.

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs [hunk 7]
```diff
@@ -17,15 +17,20 @@ import Control.DeepSeq (NFData)
...
 
--- | Staking credential used to assign rewards
+-- | Staking credential used to assign rewards.
 data StakingCredential
+    -- | The staking hash is the `Credential` required to unlock a transaction output. Either
+    -- a public key credential (`Crypto.PubKeyHash`) or
+    -- a script credential (`Scripts.ValidatorHash`). Both are hashed with /BLAKE2b-244/. 28 byte.
     = StakingHash Credential
-    | StakingPtr Integer Integer Integer -- NB: The fields should really be Word64 / Natural / Natural, but 'Integer' is our only integral type so we need to use it instead.
+    -- | NB: The fields should really be `Word64` `Natural` `Natural`,
```
Comment (bezirg) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs:31]: Do you want to say whwat the word64 , natural , natural represent? I think it is the slot number, the transaction index inside that slot and the txout index inside that transaction. Is that correct @JaredCorduan  ?

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs [hunk 8]
```diff
@@ -269,50 +269,104 @@ newtype StakeValidator = StakeValidator { getStakeValidator :: Script }
 instance Haskell.Show StakeValidator where
     show = const "StakeValidator { <script> }"
 
--- | Script runtime representation of a @Digest SHA256@.
+{- | Script runtime representation of a 28 byte hash. Hashed with /BLAKE2b-224/.
+
+This is a simple type without any validation, __use with caution__.
+You may want to add checks for its invariants. See the
+ [Shelly ledger specification](https://hydra.iohk.io/build/16861845/download/1/ledger-spec.pdf).
```
Comment (bezirg) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs:276]: typo: Shelley

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs [hunk 9]
```diff
@@ -269,50 +269,104 @@ newtype StakeValidator = StakeValidator { getStakeValidator :: Script }
...
     deriving stock (Generic)
     deriving newtype (Haskell.Eq, Haskell.Ord, Eq, Ord, ToData, FromData, UnsafeFromData)
     deriving anyclass (NFData)
 
--- | Script runtime representation of a @Digest SHA256@.
+{- | Script runtime representation of a 28 byte hash. Hashed with /BLAKE2b-224/.
+
+This is a simple type without any validation, __use with caution__.
+You may want to add checks for its invariants. See the
+ [Shelly ledger specification](https://hydra.iohk.io/build/16861845/download/1/ledger-spec.pdf).
```
Comment (bezirg) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs:293]: typo: Shelley

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs [hunk 10]
```diff
@@ -269,50 +269,104 @@ newtype StakeValidator = StakeValidator { getStakeValidator :: Script }
...
     deriving stock (Generic)
     deriving newtype (Haskell.Eq, Haskell.Ord, Eq, Ord, ToData, FromData, UnsafeFromData)
     deriving anyclass (NFData)
 
--- | Script runtime representation of a @Digest SHA256@.
+{- | Script runtime representation of a 32 byte hash. Hashed with /BLAKE2b-256/.
+
+This is a simple type without any validation, __use with caution__.
+You may want to add checks for its invariants. See the
+ [Shelly ledger specification](https://hydra.iohk.io/build/16861845/download/1/ledger-spec.pdf).
```
Comment (bezirg) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs:310]: typo

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs [hunk 11]
```diff
@@ -269,50 +269,104 @@ newtype StakeValidator = StakeValidator { getStakeValidator :: Script }
...
```
Comment (bezirg) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs:327]: typo

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs [hunk 12]
```diff
@@ -269,50 +269,104 @@ newtype StakeValidator = StakeValidator { getStakeValidator :: Script }
...
     deriving stock (Generic)
     deriving newtype (Haskell.Eq, Haskell.Ord, Eq, Ord, ToData, FromData, UnsafeFromData)
     deriving anyclass (NFData)
 
--- | Script runtime representation of a @Digest SHA256@.
+{- | Script runtime representation of a 28 byte hash. Hashed with /BLAKE2b-224/.
+
+This is a simple type without any validation, __use with caution__.
+You may want to add checks for its invariants. See the
+ [Shelly ledger specification](https://hydra.iohk.io/build/16861845/download/1/ledger-spec.pdf).
```
Comment (bezirg) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs:344]: typo

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs [hunk 13]
```diff
@@ -269,50 +269,104 @@ newtype StakeValidator = StakeValidator { getStakeValidator :: Script }
...
```
Comment (bezirg) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs:361]: typo

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Tx.hs [hunk 14]
```diff
@@ -59,32 +59,41 @@ import PlutusLedgerApi.V1.Bytes
 import PlutusLedgerApi.V1.Crypto
 import PlutusLedgerApi.V1.Scripts
 import PlutusLedgerApi.V1.Value
+{- | A transaction ID. Hashed with BLAKE2b-256. 32 byte.
 
--- | A transaction ID, using a SHA256 hash as the transaction id.
+This is a simple type without any validation, __use with caution__.
+You may want to add checks for its invariants. See the
+ [Shelly ledger specification](https://hydra.iohk.io/build/16861845/download/1/ledger-spec.pdf).
```
Comment (bezirg) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Tx.hs:66]: typo

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs [hunk 15]
```diff
@@ -53,36 +53,47 @@ import Prelude qualified as Haskell
...
+import PlutusTx.These (These (..))
+import Prettyprinter (Pretty, (<>))
+import Prettyprinter.Extras (PrettyShow (PrettyShow))
 
+{- | ByteString representing the currency, hashed with /BLAKE2b-224/.
+It is empty for `Ada`, 28 bytes for `PolicyId`.
+
+This is a simple type without any validation, __use with caution__.
+You may want to add checks for its invariants. See the
+ [Shelly ledger specification](https://hydra.iohk.io/build/16861845/download/1/ledger-spec.pdf).
```
Comment (bezirg) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs:78]: typo

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs [hunk 16]
```diff
@@ -91,18 +102,26 @@ currencyMPSHash (CurrencySymbol h) = MintingPolicyHash h
...
 currencySymbol = CurrencySymbol . PlutusTx.toBuiltin
 
--- | ByteString of a name of a token, shown as UTF-8 string when possible
+{- | ByteString of a name of a token, hashed with /BLAKE2b-256/.
+Shown as UTF-8 string when possible.
+Should be no longer than 32 bytes, empty for Ada.
+
+This is a simple type without any validation, __use with caution__.
+You may want to add checks for its invariants. See the
+ [Shelly ledger specification](https://hydra.iohk.io/build/16861845/download/1/ledger-spec.pdf).
```
Comment (bezirg) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs:111]: typo

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Crypto.hs [hunk 17]
```diff
@@ -18,11 +18,20 @@ import PlutusTx.Lift (makeLift)
 import PlutusTx.Prelude qualified as PlutusTx
 import Prettyprinter
 
--- | The hash of a public key. This is frequently used to identify the public key, rather than the key itself.
+{- | The hash of a public key. This is frequently used to identify the public key,
+rather than the key itself. Hashed with /BLAKE2b-224/. 28 bytes.
+
+This is a simple type without any validation, __use with caution__.
+You may want to add checks for its invariants. See the
+ [Shelly ledger specification](https://hydra.iohk.io/build/16861845/download/1/ledger-spec.pdf).
```
Comment (bezirg) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Crypto.hs:26]: typo

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Bytes.hs (hunk 6 above)
Comment (bezirg) [reply plutus-ledger-api/src/PlutusLedgerApi/V1/Bytes.hs:91]: Ah no, it was just a general comment, not to be fixed by this PR (if it needs fixing)

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs (hunk 7 above)
Comment (bezirg) [reply plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs:31]: Actually after reading the shelley spec, the `Word64` may even be wrong, because under "B.4 Payloads" of https://hydra.iohk.io/build/16861845/download/1/ledger-spec.pdf    it says :

> pointer address one 28-byte bytestring, and **three variable-length** unsigned integers

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Time.hs [hunk 18]
```diff
@@ -35,7 +35,8 @@ newtype DiffMilliSeconds = DiffMilliSeconds Integer
 
 makeLift ''DiffMilliSeconds
 
--- | POSIX time is measured as the number of milliseconds since 1970-01-01T00:00:00Z
+-- | POSIX time is measured as the number of milliseconds since 1970-01-01T00:00:00Z.
+-- Must be non-negative.
```
Comment (bezirg) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Time.hs:39]: Where does it say that it cannot be negative? Especially since POSIXTime is used as an `Interval` why the lower bound cannot be negative? @michaelpj

Comment (bezirg) [reply plutus-ledger-api/src/PlutusLedgerApi/V1/Time.hs:39]: POSIXTime is seconds in c (int32 or int64) or in Haskell internally (Integer that represents picoseconds)

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs (hunk 15 above)
Comment (bezirg) [reply plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs:78]: What is PolicyId?

Comment (bezirg) [reply plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs:78]: Is PolicyID same as MintingPolicyHash?

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs [hunk 19]
```diff
@@ -53,36 +53,47 @@ import Prelude qualified as Haskell
...
+        , Haskell.Show   -- ^ using hex encoding
+        , Pretty         -- ^ using hex encoding
+        ) via LedgerBytes
     deriving stock (Generic, Data)
     deriving newtype (Haskell.Eq, Haskell.Ord, Eq, Ord, PlutusTx.ToData, PlutusTx.FromData, PlutusTx.UnsafeFromData)
     deriving anyclass (NFData)
 
 {-# INLINABLE mpsSymbol #-}
--- | The currency symbol of a monetary policy hash
+-- | The `CurrencySymbol` of a monetary policy hash
```
Comment (bezirg) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs:91]: Oh yes, answering my own question policyid seems to be the same. Perhaps rename every PolicyId occurence to MintingPolicyHash

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs (hunk 16 above)
Comment (bezirg) [reply plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs:111]: Maybe we should make clear that this has nothing to do with the mintingpolicyhash and is a non-unique arbitrary string attach to the currencysymbol/mintpolicyhash

Comment (bezirg) [reply plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs:111]: Or does it have to be unique in the AssetClass?

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs (hunk 7 above)
Comment (thealmarty) [reply plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs:31]: Yes I would like to put in more info if we have it.

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Time.hs (hunk 18 above)
Comment (thealmarty) [reply plutus-ledger-api/src/PlutusLedgerApi/V1/Time.hs:39]: I think we've confirmed that POSIXTime is in milliseconds. It was listed in one of the issues as an invariant that we should document. I thought it made sense from its existing Haddock because it's definitely after 1970?

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs (hunk 7 above)
Comment (JaredCorduan) [reply plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs:31]: The triple represents: the slot number, the transaction index (within the block), and the certificate index (within the transaction).

In the spec, "three variable-length unsigned integers" refers to the wire spec, not the haskell types.

The implementation uses a `Word64` for all three of these.

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Time.hs (hunk 18 above)
Comment (bezirg) [reply plutus-ledger-api/src/PlutusLedgerApi/V1/Time.hs:39]: Yes confimed to be milliseconds. I thought perhaps to leave a note that this is not the same as Haskell's `Data.Time.Clock.POSIX.POSIXTime`

Comment (thealmarty) [reply plutus-ledger-api/src/PlutusLedgerApi/V1/Time.hs:39]: OK I'll remove it since we're not sure.

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs (hunk 16 above)
Comment (thealmarty) [reply plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs:111]: An `AssetClass` is identified by a `CurrencySymbol` and a `TokenName` so I think `TokenName` can be anything for an `AssetClass`. A `Value` though, is a map from `CurrencySymbol`'s to a quantity of that currency, which is a map from `TokenName` to an `Integer`. So `CurrencySymbol`'s have to be unique and for each `CurrencySymbol` you need to have unique `TokenName`, otherwise there can be problems. But I think there is only one `TokenName` for each `CurrencySymbol` in an `AssetClass` so that should be fine. So the main thing is that `CurrencySymbol` have to be unique for the map to not lose info.

Comment (thealmarty) [reply plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs]: I've updated the Haddock.

Comment (thealmarty) [reply plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs]: I don't understand why `Value` isn't a map from `AssetClass` to `Integer` though.

**Review by bezirg — APPROVED** [review]

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Bytes.hs [hunk 20]
```diff
@@ -28,12 +28,14 @@ import PlutusTx
 import PlutusTx.Prelude qualified as P
 import Prettyprinter.Extras (Pretty, PrettyShow (..))
 
+{- | An error that is encountered when converting a `Bytestring` to a `LedgerBytes`. -}
```
Comment (michaelpj) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Bytes.hs:31]:
```suggestion
{- | An error that is encountered when converting a `ByteString` to a `LedgerBytes`. -}
```

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Bytes.hs [hunk 21]
```diff
@@ -28,12 +28,14 @@ import PlutusTx
...
 data LedgerBytesError =
-    UnpairedDigit
-    | NotHexit Char
+    UnpairedDigit -- ^ Odd number of bytes.
+    | NotHexit Char -- ^ Not a hex digit.
     deriving stock (Show)
     deriving anyclass (Exception)
 
+{- | Convert a hex encoded `Bytestring` to a `LedgerBytes`. May return an error (`LedgerBytesError`). -}
```
Comment (michaelpj) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Bytes.hs:38]:
```suggestion
{- | Convert a hex encoded `ByteString` to a `LedgerBytes`. May return an error (`LedgerBytesError`). -}
```

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs [hunk 22]
```diff
@@ -17,15 +17,23 @@ import Control.DeepSeq (NFData)
...
 
--- | Staking credential used to assign rewards
+-- | Staking credential used to assign rewards.
 data StakingCredential
+    -- | The staking hash is the `Credential` required to unlock a transaction output. Either
+    -- a public key credential (`Crypto.PubKeyHash`) or
+    -- a script credential (`Scripts.ValidatorHash`). Both are hashed with /BLAKE2b-244/. 28 byte.
     = StakingHash Credential
-    | StakingPtr Integer Integer Integer -- NB: The fields should really be Word64 / Natural / Natural, but 'Integer' is our only integral type so we need to use it instead.
+    -- | NB: The fields should really be all `Word64`, as they are implemented in `Word64`,
```
Comment (michaelpj) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs:31]: Can we include a sentence about what this constructor represents as well as the NB?

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs [hunk 23]
```diff
@@ -42,10 +50,15 @@ instance PlutusTx.Eq StakingCredential where
...
     _ == _ = False
 
--- | Credential required to unlock a transaction output
+-- | Credentials required to unlock a transaction output.
 data Credential
-  = PubKeyCredential PubKeyHash -- ^ The transaction that spends this output must be signed by the private key
-  | ScriptCredential ValidatorHash -- ^ The transaction that spends this output must include the validator script and be accepted by the validator.
+  =
+    -- | The transaction that spends this output must be signed by the private key.
+    -- Hashed with /BLAKE2b-244/. 28 byte. See `Crypto.PubKeyHash`.
```
Comment (michaelpj) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs:57]: I don't think we need to repeat this here since it's on the documentation of the inner type.

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs [hunk 24]
```diff
@@ -42,10 +50,15 @@ instance PlutusTx.Eq StakingCredential where
...
+    PubKeyCredential PubKeyHash
+    -- | The transaction that spends this output must include the validator script and
+    -- be accepted by the validator. Hashed with /BLAKE2b-244/. 28 byte. See `Scripts.ValidatorHash`.
```
Comment (michaelpj) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Credential.hs:60]: ditto

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs [hunk 25]
```diff
@@ -223,50 +223,104 @@ newtype StakeValidator = StakeValidator { getStakeValidator :: Script }
 instance Haskell.Show StakeValidator where
     show = const "StakeValidator { <script> }"
 
--- | Script runtime representation of a @Digest SHA256@.
+{- | Script runtime representation of a 28 byte hash. Hashed with /BLAKE2b-224/.
```
Comment (michaelpj) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Scripts.hs:226]: Perhaps it's closer to say it's the "Type representing a hash of a script"? And then similarly below but for hashes of validators, datums, etc. That's the main purpose of the type, to help you remember what kind of thing it's a hash of.

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Tx.hs [hunk 26]
```diff
@@ -48,32 +48,41 @@ import PlutusLedgerApi.V1.Bytes
 import PlutusLedgerApi.V1.Crypto
 import PlutusLedgerApi.V1.Scripts
 import PlutusLedgerApi.V1.Value
+{- | A transaction ID. Hashed with BLAKE2b-256. 32 byte.
```
Comment (michaelpj) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Tx.hs:51]:
```suggestion
{- | A transaction ID, i.e. the hash of a transaction. Hashed with BLAKE2b-256. 32 byte.
```

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs [hunk 27]
```diff
@@ -53,36 +53,50 @@ import Prelude qualified as Haskell
...
-
+import PlutusTx.These (These (..))
+import Prettyprinter (Pretty, (<>))
+import Prettyprinter.Extras (PrettyShow (PrettyShow))
+
+{- | ByteString representing the currency, hashed with /BLAKE2b-224/.
+It is empty for `Ada`, 28 bytes for `MintingPolicyHash`.
+Forms an `AssetClass` along with `TokenName`.
+A `Value` is a map from `CurrencySymbol`'s to a map from `TokenName` to an `Integer`.
+So `CurrencySymbol` should be unique for `Value` to contain all currencies.
```
Comment (michaelpj) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs:77]: I don't understand this sentence?

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs [hunk 28]
```diff
@@ -91,18 +105,27 @@ currencyMPSHash (CurrencySymbol h) = MintingPolicyHash h
 currencySymbol :: BS.ByteString -> CurrencySymbol
 currencySymbol = CurrencySymbol . PlutusTx.toBuiltin
 
--- | ByteString of a name of a token, shown as UTF-8 string when possible
+{- | ByteString of a name of a token, hashed with /BLAKE2b-256/.
```
Comment (michaelpj) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs:108]: Token names aren't hashes! They're just arbitrary bytestrings (with a fixed length).

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs [hunk 29]
```diff
@@ -145,21 +170,28 @@ newtype AssetClass = AssetClass { unAssetClass :: (CurrencySymbol, TokenName) }
...
--- 'Value'. The effect of this is that the currencies in the 'Value' are "independent",
--- and are operated on separately.
---
--- Whenever we need to get the quantity of a currency in a 'Value' where there
--- is no explicit quantity of that currency in the 'Value', then the quantity is
--- taken to be zero.
---
--- See note [Currencies] for more details.
+{- | The 'Value' type represents a collection of amounts of different currencies.
+This is a map from 'CurrencySymbol's to a quantity of that currency.
```
Comment (michaelpj) [inline plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs:174]: kind of, it's a map from currency symbols to token names to quantities. I wouldn't say it's directly a map to quantities. also I wouldn't describe it as a map ;) it's a finitely-supported function! or the vector space analogy is fine

**Review by michaelpj — APPROVED** [review]

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs (hunk 29 above)
Comment (thealmarty) [reply plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs:174]:
```suggestion
```

File: plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs (hunk 27 above)
Comment (thealmarty) [reply plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs:77]: let's not worry about it then.
```suggestion
```

**Comment by kwxm** [comment]
Seems to be stuck in CI, so I'm going to merge anyway.
