### PR TITLE
[Bug] [PLC] [Builtin] [Evaluation] Added environment discharging to fix #1882

### LINKED ISSUE #1882: Polymorphic functions subvert the CEK machine
With `Bool` in the universe and `ifThenElse` defined like that:

```haskell
typedIfThenElse
    :: (GShow uni, GEq uni, uni `IncludesAll` '[BSL.ByteString, Bool])
    => TypedBuiltinName uni '[Bool, OpaqueTerm uni "a" 0, OpaqueTerm uni "a" 0] (OpaqueTerm uni "a" 0)
typedIfThenElse =
    TypedBuiltinName IfThenElse $
        TypeSchemeAllType Proxy $ \a ->
            Proxy `TypeSchemeArrow` a `TypeSchemeArrow` a `TypeSchemeArrow` TypeSchemeResult a

applyBuiltinName IfThenElse  =
    applyTypedBuiltinName typedIfThenElse (\b x y -> if b then x else y) (\_ _ _ -> ExBudget 1 1)

-- > /\(A :: *) -> \(b : Bool) (x y : () -> A) -> ifThenElse {() -> A} b x y ()
ifThenElse :: (TermLike term TyName Name uni, uni `IncludesAll` '[Bool, ()], Rename (term ())) => term ()
ifThenElse = runQuote $ rename =<< do
    a <- freshTyName () "a"
    b <- freshName () "b"
    x <- freshName () "x"
    y <- freshName () "y"
    let unitFunA = TyFun () unit (TyVar () a)
    return
       . tyAbs () a (Type ())
      $ mkIterLamAbs [
          VarDecl () b bool,
          VarDecl () x unitFunA,
          VarDecl () y unitFunA
          ]
      $ mkIterApp ()
          (tyInst () (builtinNameAsTerm IfThenElse) unitFunA)
          [var () b, var () x, var () y, unitval]
```

and this term

```haskell

appliedIfThenElse :: Term TyName Name DefaultUni ()
appliedIfThenElse =
    let int = mkTyBuiltin @Integer ()
        instConst = Apply () $ mkIterInst () Function.const [int, unit]
    in
            mkIterApp ()
                (TyInst () ifThenElse int)
                [mkConstant () True, instConst $ mkConstant @Integer () 0, instConst $ mkConstant @Integer () 1]
```

which in the readable syntax looks like that:

```
(/\(a_4 :: *) -> \(b_5 : bool) -> \(x_6 : unit -> a_4) -> \(y_7 : unit -> a_4) ->
    ifThenElse {unit -> a_4} b_5 x_6 y_7 ())
  {integer}
  True
  ((/\(a_0 :: *) -> /\(b_1 :: *) -> \(x_2 : a_0) -> \(y_3 : b_1) -> x_2) {integer} {unit} 0)
  ((/\(a_0 :: *) -> /\(b_1 :: *) -> \(x_2 : a_0) -> \(y_3 : b_1) -> x_2) {integer} {unit} 1)
```

the CEK machine fails to evaluate the term:

```
*** Exception: An error has occurred:  Cannot evaluate an open term.
Caused by: (x_2)
```

The following term:

```
(/\(a_4 :: *) -> \(b_5 : bool) -> \(x_6 : unit -> a_0) -> \(y_7 : unit -> a_4) ->
    x_6 ())
  {integer}
  True
  ((/\(a_0 :: *) -> /\(b_1 :: *) -> \(x_2 : a_0) -> \(y_3 : b_1) -> x_2) {integer} {unit} 0)
  ((/\(a_0 :: *) -> /\(b_1 :: *) -> \(x_2 : a_0) -> \(y_3 : b_1) -> x_2) {integer} {unit} 1)
```

which is supposed to behave equally to the previous one doesn't cause the CEK machine to crash.

The original term is handled correctly by the CK machine (evaluation results in `con 0`).

It seems, we can't return an open term from a built-in function application even if that open term is literally one of the arguments of the function, which is super counter-intuitive.

Things to do:

1. add a self-contained test
2. figure out why the CEK machine behaves like it behaves
3. hopefully fix the behaviour

### PR DESCRIPTION
**Pull request by effectfully**
See https://github.com/input-output-hk/plutus/issues/1882

### CODE REVIEW

File: language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs [hunk 1]
```diff
@@ -221,7 +229,8 @@ computeCek con t@(Var _ varName)   = do
 returnCek
     :: (GShow uni, GEq uni, DefaultUni <: uni, Closed uni, uni `Everywhere` ExMemoryUsage)
     => Context uni -> WithMemory Value uni -> CekM uni (Plain Term uni)
-returnCek [] res = pure $ void res
+-- Instantiate all the free variable of the resulting term in case there are any.
```
Comment (michaelpj) [inline language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs]: :+1:

Comment (michaelpj) [reply language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs]: This would only be possible if someone actually started the original `computeCek` with a non-empty environment, right?

File: language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs [hunk 2]
```diff
@@ -178,6 +179,13 @@ lookupDynamicBuiltinName dynName = do
             term = Builtin () $ DynBuiltinName () dynName
         Just mean -> pure mean
 
+-- | Instantiate all the free variables of a term by looking them up in an environment.
+dischargeVarEnv :: VarEnv uni -> WithMemory Term uni -> WithMemory Term uni
+dischargeVarEnv varEnv =
+    termSubstFreeNames $ \name -> do
```
Comment (michaelpj) [inline language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs]: I recall that the CEK machine allows name shadowing/non-global renaming. This is mentioned in the module header, but perhaps deserves a standalone note.

File: language-plutus-core/src/Language/PlutusCore/Subst.hs [hunk 3]
```diff
@@ -95,20 +97,49 @@ typeSubstTyNames
...
--- | Naively substitute type names using the given functions (i.e. do not substitute binders).
+-- | Naively substitute type names using the given function (i.e. do not substitute binders).
 termSubstTyNames
     :: (tyname ann -> Maybe (Type tyname uni ann))
     -> Term tyname name uni ann
     -> Term tyname name uni ann
 termSubstTyNames = purely termSubstTyNamesM
 
+-- | Monadically substitute *free* names using the given function.
+termSubstFreeNamesA
```
Comment (michaelpj) [inline language-plutus-core/src/Language/PlutusCore/Subst.hs]: I find it a little weird that this one is an `A` rather than an `M` like the others, but I guess if you can get away with the lesser constraint you might as well!

File: language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs [hunk 4]
```diff
@@ -178,6 +179,13 @@ lookupDynamicBuiltinName dynName = do
...
+        Closure varEnv' term' <- lookupName name varEnv
+        Just $ dischargeVarEnv varEnv' term'
```
[the remark this answers is not in the document]
Comment (effectfully) [reply language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs]: Thanks, I'll just copypaste your reasoning.

File: language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs (hunk 1 above)
Comment (effectfully) [reply language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs]: No. Thanks for the reminder. The lack of "environment discharging" is the reason why we still use the CK machine in `PlcTestUtils`. Otherwise the `sameEmptyRoseEval` test of `plutus-tx-plugin` fails. Basically if evaluation results in a non-constant, then that non-constant can have uninstantiated variables in it. We've discussed that somewhat recently, but I'm unable to find the discussion.

I'll update the `PlcTestUtils` module to finally use the CEK machine.

File: language-plutus-core/src/Language/PlutusCore/Subst.hs (hunk 3 above)
Comment (effectfully) [reply language-plutus-core/src/Language/PlutusCore/Subst.hs]: It's not just about the lesser constraint, it also immediately gives the reader an idea of how the algorithm works. Namely that we do not recurse after calling `f` over a name, which is an option given that the result of this operation is a `Term`. And it's clear that we don't do that, because we'd have to be in a monad for that.

In general, I find it helpful to distinguish between applicatively and monadically effectful functions (I'll also update the comment to say "Applicatively"), especially given that certain functions have both the variants (e.g. `foldMapA` vs `foldMapM` -- the former is good for a lazy applicative and a non-constant-space monoid, the later is good for a strict monad and a constant-space monoid).

File: language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs (hunk 2 above)
Comment (effectfully) [reply language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs]: I'd expect people studying the code to read the module header. What's the point of duplicating the same note twice in a single file? Especially when the note is already in the "prime space".

Comment (michaelpj) [reply language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs]: Well, in this instance I thought: "hm, does the CEK machine assume globally renamed variables?". Grepped for "renamed", nothing, no note references, eventually I looked in the header.

If you just want to put it in the header then maybe reference it from here.

File: language-plutus-core/src/Language/PlutusCore/Subst.hs (hunk 3 above)
Comment (michaelpj) [reply language-plutus-core/src/Language/PlutusCore/Subst.hs]: I guess I wonder whether the other ones could be `Applicative`.

File: language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs (hunk 1 above)
Comment (michaelpj) [reply language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs]: Sounds good, although we should have some tests to cross-check them somewhere.

File: language-plutus-core/src/Language/PlutusCore/Subst.hs (hunk 3 above)
Comment (effectfully) [reply language-plutus-core/src/Language/PlutusCore/Subst.hs]: There's `substTyVarA` and `substVarA`. Others can't be applicatively effectful, because `transformM` that they use under the hood is monadic as it has a similar behaviour to

> recurse after calling `f` over a name, which is an option given that the result of this operation is a Term

File: language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs (hunk 2 above)
Comment (effectfully) [reply language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs]: I'll do that, but why here? Global uniqueness is as related here as in all other places in this module.

File: language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs (hunk 1 above)
Comment (effectfully) [reply language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs]: Added a test and checked that the behaviour of the CEK machine has indeed changed.

File: language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs (hunk 2 above)
Comment (effectfully) [reply language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs]: Added a separate note.

Comment (michaelpj) [reply language-plutus-core/src/Language/PlutusCore/Evaluation/Machine/Cek.hs]: I guess the question of where the note is relevant is something of a matter of taste. Here it seems to me that it's definitely relevant, but I agree it's somewhat relevant in a lot of places...

**Comment by effectfully** [comment]
> Oh, hold on. Is there a genuine danger that we'll ever want to do something fancy with extensible builtins that will require expensive substitutions in arguments being passed to builtins (lists or something)? That might complicate execution costing substantially.

Yes, it's a very real danger. I'm just fixing a bug here by implementing something that we anyway need (environment discharging allows to use the CEK machine where it was only possible to use the CK machine). I do believe we should come up with a better solution to the polymorphic built-in function evaluation problem. I've drafted a possible solution in #1882 

> My only (minor) concern is that we have to do some extra work at the end of validation, when we discharge the final enviroment to get a result whose exact value is unimportant during validation (we only care if it's error or not). It seems improbable (?) that validators will be returning complex terms though, so this probably won't be too expensive in practice.

> That says that the CEK machine returns a pair `(V,ρ)` (value + environment) to the caller, so we can say that either the machine substitutes the contents of `ρ` into `V` before returning, or that it's up to the caller to do that.

Agreed, it'd make sense to add more granularity here and let the caller decide whether they want to discharge the environment or not. But I want to get the bug fixed and continue ditching unlifting as I'm running out of time (need to return to Midnight soon), so I guess someone else will have to implement the improvement.

**Comment by effectfully** [comment]
Ok, merging.
