### PR TITLE
SCP-2494: Remove thread token from previous value of a state machine step

### LINKED ISSUE #3546: runStep does result in InsufficientFunds when using a threadToken
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[x] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Summary

When using a thread token with `Plutus.Contract.StateMachine`, `runInitialise` correctly pays it to the script, but a following `runStep` fails with `InsufficientFunds`.

The issue was observed in our integrated code as well as a in minimal [reproducer example](https://github.com/input-output-hk/hydra-poc/blob/43d3ed255d350c2f379b16860502939de16b3137/hydra-plutus/exe/sm-repro/Main.hs):
```
λ cabal exec sm-repro
Slot 00000: TxnValidate af5e6d25b5ecb26185289a03d50786b7ac4425b21849143ed7e18bcd70dc4db8
Slot 00000: SlotAdd Slot 1
Slot 00001: 00000000-0000-4000-8000-000000000000 {Contract instance for wallet 1}:
  Contract instance started
Slot 00001: *** CONTRACT LOG: "Forged thread token: ThreadToken {ttOutRef = TxOutRef {txOutRefId = af5e6d25b5ecb26185289a03d50786b7ac4425b21849143ed7e18bcd70dc4db8, txOutRefIdx = 6}, ttCurrencySymbol = 6611d7baf973a1d9e64c60c546cafbe94a3ab7ce4928dd97d768c913066bc4d6}"
Slot 00001: W1: TxSubmit: 3f1ebb918adf02ccdcdd8ff82f354e2bc346f180b734cdf41c8a4529cf9c9b54
Slot 00001: TxnValidate 3f1ebb918adf02ccdcdd8ff82f354e2bc346f180b734cdf41c8a4529cf9c9b54
Slot 00001: SlotAdd Slot 2
Slot 00002: *** CONTRACT LOG: "Initialized state machine"
Slot 00002: *** CONTRACT STOPPED WITH ERROR: "\"SMCContractError (WalletError (InsufficientFunds \\\"Total: Value (Map [(,Map [(\\\\\\\"\\\\\\\",99992792)])]) expected: Value (Map [(6611d7baf973a1d9e64c60c546cafbe94a3ab7ce4928dd97d768c913066bc4d6,Map [(0x715d66b53561035ba0b0881776b7d2054c73d3b0eb1fb6aabb0229d36345b33a,1)])])\\\"))\""
```

## Steps to reproduce

1. Checkout https://github.com/input-output-hk/hydra-poc/tree/plutus-sm-repro
2. `cabal build hydra-plutus:exe:sm-repro`
3. `cabal exec sm-repro`

## Expected behavior

When using the `Plutus.Contract.Statemachine` interface, we expect that thread tokens are handled for us and that no additional constraints / lookups would be necessary for handling the state machine's thread token.

## System info (please complete the following information):

- OS: NixOS 21.05
- Plutus: bfc2e4a3f598115d50b3fa685089d97f2f5f30e9

## Additional context

I did look into the Auction use case (which we took as an example originally) and while the tests do seem to pass:
```
> defaultMain tests
auction
  run an auction:                    OK (1.16s)
  run an auction with multiple bids: OK (1.53s)
  QuickCheck property:               OK
    +++ OK, passed 1 test (100% FIXME).
All 3 tests passed (2.70s)
*** Exception: ExitSuccess
```
running the `auctionTrace1` with `runEmulatorTraceIO` is blocking (?) and simply activating the [`auctionSeller`](https://github.com/input-output-hk/plutus/blob/bfc2e4a3f598115d50b3fa685089d97f2f5f30e9/plutus-use-cases/src/Plutus/Contracts/Auction.hs#L209) contract (which is quite similar to the [reproducer contract](https://github.com/input-output-hk/hydra-poc/blob/43d3ed255d350c2f379b16860502939de16b3137/hydra-plutus/exe/sm-repro/Main.hs#L65)) gives me also the `InsufficientFunds` error !?
```
> runEmulatorTraceIO $ void $ Trace.activateContractWallet w1 seller
Slot 00000: TxnValidate af5e6d25b5ecb26185289a03d50786b7ac4425b21849143ed7e18bcd70dc4db8
Slot 00000: SlotAdd Slot 1
Slot 00001: 00000000-0000-4000-8000-000000000000 {Contract instance for wallet 1}:
  Contract instance started
Slot 00001: 00000000-0000-4000-8000-000000000000 {Contract instance for wallet 1}:
  Contract log: Object (fromList [("contents",Object (fromList [("contents",Object (fromList [("contents",Object (fromList [("contents",String "Total: Value (Map []) expected: Value (Map [(ffff,Map [(\"token\",1)])])"),("tag",String "InsufficientFunds")])),("tag",String "WalletError")])),("tag",String "SMCContractError")])),("tag",String "AuctionFailed")])
Slot 00001: *** CONTRACT STOPPED WITH ERROR: "StateMachineContractError (SMCContractError (WalletError (InsufficientFunds \"Total: Value (Map []) expected: Value (Map [(ffff,Map [(\\\"token\\\",1)])])\")))"
Slot 00001: SlotAdd Slot 2
```

### PR DESCRIPTION
**Pull request by sjoerdvisscher**
Fixes #3546

Pre-submit checklist:
- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
    - [x] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

### CODE REVIEW

File: plutus-contract/src/Plutus/Contract/StateMachine.hs [hunk 1]
```diff
@@ -462,7 +462,7 @@ mkStep client@StateMachineClient{scInstance} input = do
         Nothing -> pure $ Left $ InvalidTransition Nothing input
         Just (onChainState, utxo) -> do
             let (TypedScriptTxOut{tyTxOutData=currentState, tyTxOutTxOut}, txOutRef) = onChainState
-                oldState = State{stateData = currentState, stateValue = Ledger.txOutValue tyTxOutTxOut}
+                oldState = State{stateData = currentState, stateValue = Ledger.txOutValue tyTxOutTxOut <> inv (SM.threadTokenValueOrZero scInstance)}
```
Comment (michaelpj) [inline plutus-contract/src/Plutus/Contract/StateMachine.hs:465]: Both of these are worth a comment!

Comment (michaelpj) [reply plutus-contract/src/Plutus/Contract/StateMachine.hs:465]: Would it be simpler to rather only add the token value to the current value in the transition where we mint it?

Comment (sjoerdvisscher) [reply plutus-contract/src/Plutus/Contract/StateMachine.hs:465]: We need to keep adding it because the transition can just ignore the old value. In fact all our tests did this, that’s why this bug did not surface earlier.

Comment (michaelpj) [reply plutus-contract/src/Plutus/Contract/StateMachine.hs:465]: I see. Maybe we really want something like `(\/) :: Value -> Value -> Value` so we could write `newValue = transitionValue \/ threadTokenValue` or something.

Comment (michaelpj) [reply plutus-contract/src/Plutus/Contract/StateMachine.hs:465]: What am I talking about, we literally have that.

Comment (michaelpj) [reply plutus-contract/src/Plutus/Contract/StateMachine.hs:465]: Okay, so I suggest we do that: that lets us always add it in without duplicating.

Comment (sjoerdvisscher) [reply plutus-contract/src/Plutus/Contract/StateMachine.hs]: I think it is actually nice to hide the thread token value from the client code? I haven't seen examples where the oldValue is used, but I guess if you want to do something with that it would be convenient if you don't have to take the thread token value into account.

Comment (michaelpj) [reply plutus-contract/src/Plutus/Contract/StateMachine.hs]: Oh I see, so the idea is that the transition function never sees the thread token at all. That's a good point, I guess. I'm not sure what is nicer.

**Review by j-mueller — APPROVED** [review]
